playing catchup with a bunch of offline updates

diff --git a/global-slack/files/etc/default/slack-functions b/global-slack/files/etc/default/slack-functions
--- a/global-slack/files/etc/default/slack-functions
+++ b/global-slack/files/etc/default/slack-functions
@@ -9,12 +9,35 @@ DATESTRING=`date +%m_%d_%Y_%H_%M_%S`
 
 __cleanup()
 {
-find /var/lib/slack/backups -type d  -mtime +14  -exec rm -rf {} \;
+find /var/lib/slack/backups -type d  -mtime +7  -exec rm -rf {} \;
 
 find /var/cache/slack/roles -mtime +14 -name \*.zip -exec rm -rf {} \;
 
 mkdir -p /var/lib/slack/backups
 mkdir -p /var/cache/slack/roles
+
+}
+
+__newcleanup()
+{
+cd /var/lib/slack/backups || return
+
+for dir in * ; do
+####  perl -MTime::Local -e 'print int(timelocal(7,30,8,1,9,2014))'
+  YEAR=`echo "${dir}"|awk -F\- {'print $1'}|perl -p -e "s|^[0]+|0|g"|perl -p -e "s|^[0]+([0-9]+)|\1|g"` ; test "X${YEAR}" = "X" && return
+  MONTH=`echo "${dir}"|awk -F\- {'print $2-1'}|perl -p -e "s|^[0]+|0|g"|perl -p -e "s|^[0]+([0-9]+)|\1|g"` ; test "X${MONTH}" = "X" && return
+  DAY=`echo "${dir}"|awk -F\- {'print $3'}|perl -p -e "s|^[0]+|0|g"|perl -p -e "s|^[0]+([0-9]+)|\1|g"` ; test "X${DAY}" = "X" && return
+  HOUR=`echo "${dir}"|awk -F\- {'print $4'}|awk -F\: {'print $1'}|perl -p -e "s|^[0]+|0|g"|perl -p -e "s|^[0]+([0-9]+)|\1|g"` ; test "X${HOUR}" = "X" && return
+  MIN=`echo "${dir}"|awk -F\- {'print $4'}|awk -F\: {'print $2'}|perl -p -e "s|^[0]+|0|g"|perl -p -e "s|^[0]+([0-9]+)|\1|g"` ; test "X${MIN}" = "X" && return
+  SEC=`echo "${dir}"|awk -F\- {'print $4'}|awk -F\: {'print $3'}|perl -p -e "s|^[0]+|0|g"|perl -p -e "s|^[0]+([0-9]+)|\1|g"` ; test "X${SEC}" = "X" && return
+  BKUPDIRDATE=`perl -MTime::Local -e "print int(timelocal(${SEC},${MIN},${HOUR},${DAY},${MONTH},${YEAR}))"` ; test "X${BKUPDIRDATE}" = "X" && return
+  echo ${BKUPDIRDATE}
+  NOW=`__getepoc` ; test "X${NOW}" = "X" && return
+  AGE=`expr ${NOW} - ${BKUPDIRDATE}`  ; test "X${AGE}" = "X" && return
+  test "${AGE}" -ge 1209600 && echo "${dir} should be deleted"
+
+  ##1209600
+done
 
 }
 
@@ -31,8 +54,8 @@ fi
 
 __MYLDAPSERVERLIST="${LDAPSERVER}"
 if [ -z "${__MYLDAPSERVERLIST}" ] ; then
- if [ -f /etc/slack-slaper.conf ] ; then
-  __MYLDAPSERVERLIST=`grep "^SOURCE=\"ldap" /etc/slack-slaper.conf|awk -F= {'print $2'}|grep "ldap"|perl -p -e "s/ldaps\:\/\///g"|perl -p -e "s/ldap\:\/\///g"|perl -p -e "s/\///g"|perl -p -e "s/\"//g"`
+ if [ -f /etc/slack-get.conf ] ; then
+  __MYLDAPSERVERLIST=`grep "^SOURCE=\"ldap" /etc/slack-get.conf|awk -F= {'print $2'}|grep "ldap"|perl -p -e "s/ldaps\:\/\///g"|perl -p -e "s/ldap\:\/\///g"|perl -p -e "s/\///g"|perl -p -e "s/\"//g"`
   if [ -z "${__MYLDAPSERVERLIST}" ] ; then
    echo "Error in: \$__MYLDAPSERVERLIST"
    echo "__MYLDAPSERVERLIST is null."
@@ -49,8 +72,8 @@ __SSL=""
 if [ -n "${SSL}" ] ; then
  __SSL="s"
 else
- if [ -f /etc/slack-slaper.conf ] ; then
-  __SSLTEST=`cat /etc/slack-slaper.conf|grep "^SOURCE=\"ldaps\://"`
+ if [ -f /etc/slack-get.conf ] ; then
+  __SSLTEST=`cat /etc/slack-get.conf|grep "^SOURCE=\"ldaps\://"`
   if [ -n "${__SSLTEST}" ] ; then
    __SSL="s"
   fi
@@ -247,7 +270,7 @@ fi
 SSLSTATUS=`grep "^SOURCE=\"ldaps\://%FOO%conf`
 STATUS=$?
 if [ "${STATUS}" -ne "0" ] ; then
- echo "Error in: /etc/slack-slaper.conf"
+ echo "Error in: /etc/slack-get.conf"
  echo "YAAMT require: SOURCE=\"ldaps://"
  return 1
 fi
@@ -534,13 +557,13 @@ done
 
 disableSysupdaterepos()
 {
-SYSRepos=`ls -d /etc/yum.repos.d/sysupdate.repo`
+SYSRepos=`ls -d /etc/yum.repos.d/sysupdate.repo /etc/yum.repos.d/yum-SYS-CentOS.repo /etc/yum.repos.d/yum-SYS-rhel.repo`
 test "X${SYSRepos}" != "X" && perl -p -i -e "s|^enabled=*.*$|enabled=0|g" ${SYSRepos}
 }
 
 enableSysupdaterepos()
 {
-SYSRepos=`ls -d /etc/yum.repos.d/sysupdate.repo`
+SYSRepos=`ls -d /etc/yum.repos.d/sysupdate.repo 2>/dev/null`
 test "X${SYSRepos}" != "X" && perl -p -i -e "s|^enabled=*.*$|enabled=1|g" ${SYSRepos}
 }
 
@@ -558,24 +581,24 @@ test "X${ALLRepos}" != "X" && perl -p -i -e "s|^enabled=*.*$|enabled=0|g" ${ALLR
 
 disableSiterepos()
 {
-siteRepos=`ls -d /etc/yum.repos.d/OPS-addons.repo /etc/yum.repos.d/other.distros.sysupdate.repo /etc/yum.repos.d/sysupdate.repo`
+siteRepos=`ls -d /etc/yum.repos.d/yum-SYS-contrib.repo /etc/yum.repos.d/OPS-addons.repo /etc/yum.repos.d/other.distros.sysupdate.repo /etc/yum.repos.d/sysupdate.repo /etc/yum.repos.d/yum-SYS-CentOS.repo`
 test "X${siteRepos}" != "X" && perl -p -i -e "s|^enabled=*.*$|enabled=0|g" ${siteRepos}
 }
 
 enableSiterepos()
 {
-siteRepos=`ls -d /etc/yum.repos.d/OPS-addons.repo /etc/yum.repos.d/other.distros.sysupdate.repo /etc/yum.repos.d/sysupdate.repo`
+siteRepos=`ls -d /etc/yum.repos.d/yum-SYS-*`
 test "X${siteRepos}" != "X" && perl -p -i -e "s|^enabled=*.*$|enabled=1|g" ${siteRepos}
 }
  
 enableOPSLinuxrepo()
 { 
-test -f /etc/yum.repos.d/OPS-addons.repo && perl -p -i -e "s|^enabled=*.*$|enabled=1|g" /etc/yum.repos.d/OPS-addons.repo
+test -f /etc/yum.repos.d/yum-SYS-contrib.repo  && perl -p -i -e "s|^enabled=*.*$|enabled=1|g" /etc/yum.repos.d/yum-SYS-contrib.repo
 }
 
 disableOPSLinuxrepo()
 {
-test -f /etc/yum.repos.d/OPS-addons.repo && perl -p -i -e "s|^enabled=*.*$|enabled=0|g" /etc/yum.repos.d/OPS-addons.repo
+test -f /etc/yum.repos.d/yum-SYS-contrib.repo && perl -p -i -e "s|^enabled=*.*$|enabled=0|g" /etc/yum.repos.d/yum-SYS-contrib.repo
 }
 
 enableOtherDistrorepo()
@@ -592,21 +615,29 @@ repoLinux()
 {
 ARGS="${*}"
 ACTION=`echo "${ARGS}"|awk -F\. {'print $1'}` 
-MYPKG=`echo "${ARGS}"|awk -F\. {'print $2'}|sed -e "s/,$//g"|perl -p -e "s/,/\n/g"`
-##MYPKGF=`echo "${ARGS}"|awk -F\. {'print $2'}|perl -p -e "s/,/\n/g"`
+MYPKG=`echo "${ARGS}"|perl -p -e "s|^[^\.]+\.||g"|sed -e "s/,$//g"|perl -p -e "s/,/\n/g"`
+MYPKGF=`echo "${ARGS}"|perl -p -e "s|^[^\.]+\.||g"|sed -e "s/,$//g"|perl -p -e "s/,/|/g"`
 ##MYPKGF=`echo "${MYPKGF}"|grep '.'`
 ##CURRINST=`rpm -qa --queryformat '%{NAME}\n'`
 ##ALREADYINST=`echo "${CURRINST}"|grep -F "${MYPKGF}"`
 checkrpmstatus()
 {
-NOTINST=`rpm -q --queryformat '%{NAME}\n' ${MYPKG}|grep "^package .* is not installed$"|awk {'print $2'}`
+
+####NOTINST=`for pkg in \`echo "${MYPKG}"\` ; do
+####           rpm -qa|grep "${pkg}" >/dev/null
+####           test "X${?}" != "X0" && echo "${pkg}"
+####           done`
+####
+
 if [ "X${ACTION}" = "Xinstall" ] ; then
-  MYPKG="${NOTINST}"
+  MYPKG="${MYPKG}"
+  NOTINST="${MYPKG}"
   if [ "X${NOTINST}" = "X" ] ; then
     echo "#### ALREADY INSTALLED ####"
     return 0
   else
     CURRPKGSTATE='2'
+    return 1
   fi
 fi
 }
@@ -634,42 +665,36 @@ if [ "X${CURRPKGSTATE}" = "X2" -a "X${MYPKG}" != "X" ] ; then
     disableALLrepos
     enableSysupdaterepos
     echo "#### TRYING SYSUPDATE ####"
-    SYSUPDATELIST=`/usr/bin/yum list available ${MYPKG}`
-    INSYSUPDATE="$?"
-    echo "${SYSUPDATELIST}"|awk -F. {'print $1'}|grep -F "${MYPKG}"
-    INSYSUPDATE="${INSYSUPDATE}${?}"
+####    SYSUPDATELIST=`/usr/bin/yum list available ${MYPKG}`
+####    INSYSUPDATE="$?"
+####    echo "${SYSUPDATELIST}"|awk  {'print $1'}|grep -E "(${MYPKGF})"
+####    INSYSUPDATE="${INSYSUPDATE}${?}"
+    INSYSUPDATE=`yum list available ${MYPKG} 2>/dev/null|sed -n '/^Available Packages/,$p'|grep -v "^Available Packages"|awk {'print $1'}|sort -u`
 
-    if [ "X${INSYSUPDATE}" = "X00" ] ; then
+    if [ "X${INSYSUPDATE}" != "X" ] ; then
       echo "#### PULLING FROM SYSUPDATE ####"
-      if [ "X${NOTINST}" = "X" ] ; then
-        /usr/bin/yum -y install $MYPKG
-      else
-        /usr/bin/yum -y install $NOTINST
-        if [ "X${ACTION}" = "Xupgrade" -o "X${ACTION}" = "Xupdate" ] ; then
-          /usr/bin/yum -y update $MYPKG
-        fi
+      /usr/bin/yum -y install $MYPKG
+      if [ "X${ACTION}" = "Xupgrade" -o "X${ACTION}" = "Xupdate" ] ; then
+        /usr/bin/yum -y update $MYPKG
       fi
-        
-      return 0
+      checkrpmstatus
+      test "X$?" = "X0" && return $?
     fi
 
     enableSysupdaterepos
     enableOPSLinuxrepo
     echo "#### TRYING OPSADDONS ####"
-    OPSADDONSLIST=`/usr/bin/yum list available ${MYPKG}`
-    INOPSADDONS="$?"
-    echo "${OPSADDONSLIST}"|awk -F. {'print $1'}|grep -F "${MYPKG}"
-    INOPSADDONS="${INOPSADDONS}${?}"
+####    OPSADDONSLIST=`/usr/bin/yum list available ${MYPKG}`
+####    INOPSADDONS="$?"
+####    echo "${OPSADDONSLIST}"|awk  {'print $1'}|grep -E "(${MYPKGF})"
+####    INOPSADDONS="${INOPSADDONS}${?}"
+    INOPSADDONS=`yum list available ${MYPKG} 2>/dev/null|sed -n '/^Available Packages/,$p'|grep -v "^Available Packages"|awk {'print $1'}|sort -u`
 
-    if [ "X${INOPSADDONS}" = "X00" ] ; then
+    if [ "X${INOPSADDONS}" != "X" ] ; then
       echo "#### PULLING FROM OPSADDONS ####"
-      if [ "X${NOTINST}" = "X" ] ; then
-        /usr/bin/yum -y install $MYPKG
-      else
-        /usr/bin/yum -y install $NOTINST
-        if [ "X${ACTION}" = "Xupgrade" -o "X${ACTION}" = "Xupdate" ] ; then
-          /usr/bin/yum -y update $MYPKG
-        fi
+      /usr/bin/yum -y install $MYPKG
+      if [ "X${ACTION}" = "Xupgrade" -o "X${ACTION}" = "Xupdate" ] ; then
+        /usr/bin/yum -y update $MYPKG
       fi
         
       disableOPSLinuxrepo
@@ -683,7 +708,7 @@ if [ "X${CURRPKGSTATE}" = "X2" -a "X${MYPKG}" != "X" ] ; then
       echo "#### TRYING OTHERDISTROS ####"
       OTHERDISTROSLIST=`/usr/bin/yum list available ${MYPKG}`
       INOTHERDISTROS="$?"
-      echo "${OTHERDISTROSLIST}"|awk -F. {'print $1'}|grep -F "${MYPKG}"
+      echo "${OTHERDISTROSLIST}"|awk  {'print $1'}|grep -E "(${MYPKGF})"
       INOTHERDISTROS="${INOTHERDISTROS}${?}"
 
       if [ "X${INOTHERDISTROS}" = "X00" ] ; then
@@ -820,7 +845,6 @@ return $?
 
 mktrackerLinux()
 {
-
 rm -rf  "${TSTAGE}"
 mkdir -p "${TSTAGE}" || return 12
 mkdir -p "${TWORK}/BUILD" || return 12
@@ -829,7 +853,6 @@ mkdir -p "${TWORK}/RPMS/noarch" || return 12
 mkdir -p "${TWORK}/SOURCES" || return 12
 mkdir -p "${TWORK}/SPECS" || return 12
 mkdir -p "${TWORK}/RPM_TMP" || return 12
-
 REL='1'
 
 
@@ -861,7 +884,7 @@ ${DESC}"
 
 echo "${SPECTEMPLATE}" > ${TWORK}/SPECS/${PKGNAME}-${VERSION}-${REL}.spec
 repo install.rpm-build
-rpmbuild -bb ${TWORK}/SPECS/${PKGNAME}-${VERSION}-${REL}.spec || return 13
+rpmbuild --buildroot=${TSTAGE} -bb ${TWORK}/SPECS/${PKGNAME}-${VERSION}-${REL}.spec || return 13
 rpm -Uvh ${TWORK}/RPMS/noarch/${PKGNAME}-${VERSION}-${REL}.noarch.rpm || return 14
 rm -rf ${TWORK}
 }
@@ -942,8 +965,16 @@ return $?
 rm_pkgsLinux()
 {
 test "X${*}" = "X" && return 1
-MYCURRPKGS=`rpm -q --queryformat '%{NAME}\n' ${*}|grep -v "^package .* is not installed$"|awk {'print $1'}` ; test "X${MYCURRPKGS}" = "X" && return 2
-test "X${MYCURRPKGS}" != X && rpm -e "${MYCURRPKGS}"
+####MYCURRPKGS=`rpm -qa ${*}`
+####MYCURRPKGS=`for pkg in \`echo "${*}"\` ; do
+####              rpm -qa|grep "${pkg}" >/dev/null
+####              test "X${?}" = "X0" && echo "${pkg}"
+####              done`
+MYCURRPKGS=`yum list installed ${*} 2>/dev/null|sed -n '/^Installed Packages/,$p'|grep -v "^Installed Packages"|awk {'print $1'}|sort -u`
+
+test "X${MYCURRPKGS}" = "X" && return 2
+
+test "X${MYCURRPKGS}" != X && rpm -e ${MYCURRPKGS}
 }
 
 
diff --git a/global-solaris-adminfunctions/files/etc/default/admin-functions b/global-solaris-adminfunctions/files/etc/default/admin-functions
--- a/global-solaris-adminfunctions/files/etc/default/admin-functions
+++ b/global-solaris-adminfunctions/files/etc/default/admin-functions
@@ -2,7 +2,7 @@
 
 PATH=$PATH:/sbin:/bin:/usr/sfw/bin:/usr/sfw/sbin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/opt/sfw/bin:/opt/sfw/sbin:/opt/csw/bin:/opt/csw/sbin
 #__IPLIST=`ifconfig -a|perl -p -e "s/addr\://%FOO%0"|grep "inet "|awk {'print $2'}|perl -p -e "s/\n/ /g"`
-__MYIPLIST="`ifconfig -a|grep -v "inet6"|grep "inet"|perl -p -e "s/addr\://%FOO%0.0"`"
+__MYIPLIST="`ifconfig -a|grep -v "inet6"|grep "inet"|perl -p -e "s/addr\://g"|awk {'print $2'}`"
 __MYCLASSBEES="`echo "${__MYIPLIST}"|awk -F. {'print $1"."$2'}|sort|uniq`"
 __OSNAME=`uname -s`
 __ARCH=`uname -p`
@@ -15,6 +15,7 @@ if [ "${__OSNAME}" = "SunOS" ] ; then
  __LDAPADD="/usr/local/bin/ldapadd"
  __GAWK="/opt/sfw/bin/gawk"
  __FILE="/opt/sfw/bin/gfile"
+ __STAT="/opt/sfw/bin/stat"
 else
  __FILE="file"
  __HOSTNAME=`hostname`
@@ -23,10 +24,27 @@ else
  __LDAPSEARCH="/usr/bin/ldapsearch"
  __LDAPMODIFY="/usr/bin/ldapmodify"
  __LDAPADD="/usr/bin/ldapadd"
+ __STAT="stat"
 fi
+
+
+echo "${__HOSTNAME}"|grep "\..*\..*" >/dev/null || {
+  MYENTRY=`getent hosts "${__HOSTNAME}"|awk {'print $2" "$3" "$4" "$5" "$6" "$7" "$8" "$9'}`
+
+
+  for entryli in `echo "${MYENTRY}"` ; do
+    echo "${entryli}"|grep "\..*\..*" >/dev/null && {
+      __HOSTNAME="${entryli}"
+      break
+    }
+
+  done
+
+}
 
 test "X${__HOSTNAME}" != "X" && __HOSTNAMEIP=`getent hosts ${__HOSTNAME}|head -1|awk {'print $1'}`
 
+__HOSTNAME=`echo "${__HOSTNAME}"|perl -p -e "s|\.foo\.|\.|g"|perl -p -e "s|\.foo\.|\.|g"`
 __HOSTSHORT=`echo "${__HOSTNAME}"|awk -F. {'print $1'}`
 
 nmsitehosts()
@@ -103,16 +121,16 @@ if [ "${__STATUS}" -eq "0" ] ; then
  if [ "X${revclassstatus}" = "X0" ] ; then
   __CLASSIFICATION="s"
  else
-  __CLASSIFICATION=""
+  __CLASSIFICATION="n"
  fi
 else
- __HOSTNAMEDOMAIN="`echo $__HOSTNAME|awk -F. {'foo=NF-1;foo2=NF-2;foo3=NF-3;print $foo3"."$foo2"."$foo"."$NF'}|perl -p -e "s/.*\.FOO\./FOO\./g"`"
+ __HOSTNAMEDOMAIN="`echo $__HOSTNAME|awk -F. {'foo=NF-1;foo2=NF-2;foo3=NF-3;print $foo3"."$foo2"."$foo"."$NF'}|perl -p -e "s/.*\.foo1\./foo2\./g"`"
  echo "${__HOSTNAMEDOMAIN}"|grep "class" >/dev/null
  classstatus=$? 
  if [ "X${classstatus}" = "X0" ] ; then
   __CLASSIFICATION="s"
  else
-  __CLASSIFICATION=""
+  __CLASSIFICATION="n"
  fi
 fi
 
@@ -120,12 +138,19 @@ if [ "X${__CLASSIFICATION}" = "X" ] ; then
  if [ -f /etc/default/kodak.* ] ; then
   __CLASSIFICATION="s"
  else
-  __CLASSIFICATION=""
+  __CLASSIFICATION="n"
  fi
 fi
 
+__getepoc_day()
+{
+perl -e 'print int(time/(60*60*24))'
+}
+
 __getepoc()
 {
+perl -e 'print int(time)' 2>/dev/null && return 0
+
 if ls ${__GAWK} >/dev/null 2>&1 ; then
   echo |${__GAWK} '{print systime()}'
 fi
@@ -137,7 +162,7 @@ host="$1"
 test "X${host}" = "X" && host="${__HOSTNAME}"
 ##1ST WE ATTEMPT TO DETERMINE THE SERVERS DNSDOMAIN IN A TRADITIONAL FASHION##
 
-if echo "$__HOSTNAMEDOMAIN"|grep ".FOO." >/dev/null ; then
+if echo "$__HOSTNAMEDOMAIN"|grep "\..*\..*" >/dev/null ; then
  __DNSDOMAIN="$__HOSTNAMEDOMAIN"
 elif echo "$__REVERSEDDOMAIN"|grep ".FOO." >/dev/null ; then
 ##IF THE LOCALHOSTNAME ISNT SET YOU ARE PROBABLY BEING JUMPED, SO WE THEN TRY AND REVERSE THE DNSDOMAIN THRU A CGI ON THE JUMP SERVER BY DNS REVERSING THE JUMPSERVERS FQDN##
@@ -150,7 +175,7 @@ else
 fi
 
 if echo "${host}"|grep "%FOO%" >/dev/null ; then
- __SITE=ps1
+ __SITE=ps1prod
  if echo "${host}"|grep "%FOO%" >/dev/null ; then
   __SITE=ppi
  fi
@@ -165,8 +190,8 @@ else
  echo "Error in:"
  echo "/usr/bin/hostname"
  echo "${host} contains no known datacenter site identifier."
- echo "Defaulting to __SITE=ps1"
- __SITE=ps1
+ echo "Defaulting to __SITE=ps1prod"
+ __SITE=ps1prod
 
  for ipli in `echo "${__MYCLASSBEES}"` ; do
   sitetest=`echo "${__SITEMATRIX}"|grep "^${ipli}"`
@@ -177,8 +202,8 @@ else
    echo "Error in:"
    echo "__MYIPLIST"
    echo "$__MYIPLIST contains no known datacenter ip ranges."
-   echo "Defaulting to __SITE=ps1"
-   __SITE=ps1
+   echo "Defaulting to __SITE=ps1prod"
+   __SITE=ps1prod
   fi
  done
  return 0
@@ -200,6 +225,7 @@ fi
 _HOSTNAME="$1"
 echo "${_HOSTNAME}"|grep '^X' >/dev/null
 NOLDAPLOOKUP="$?"
+NOLDAPLOOKUP="0"
 if [ "X${NOLDAPLOOKUP}" != "X0" ] ; then
  __CUSTOMERBLOB="`__ldapsearchhandler -b ou=${_HOSTNAME},ou=hosts,${__LDAPDN} -LLL`"
  __STATUS="$?"
@@ -229,7 +255,7 @@ else
   fi
  done
 
- __cmEnable=`echo "${__CUSTOMERBLOB}"|grep "^cmEnable: "|perl -p -e "s/^cmEnable\: /cmEnable\=/g"|awk -F\= {'print $2'}`
+ __cmEnable=`echo "${__CUSTOMERBLOB}"|grep -i "^cmEnable: "|perl -p -e "s/^cm[E,e].nable\: /cmenable\=/g"|awk -F\= {'print $2'}`
  if [ -n "${__CI}" -a "X${__CI}" != "XUNKNOWN" ] ; then
   echo "__CI=${__CI}"
   if [ -n "${__cmEnable}" ] ; then
@@ -258,7 +284,7 @@ rm -rf /var/lib/slack/stage/roles/slapjob*
 /usr/sbin/slack-cleanup
 
 mkdir -p /var/cache/slack/roles/slapjob$$/scripts
-cp /usr/sbin/slack-slaper /var/cache/slack/roles/slapjob$$/slapjob
+cp /usr/sbin/slack-get /var/cache/slack/roles/slapjob$$/slapjob
 chmod 555 /var/cache/slack/roles/slapjob$$/slapjob
 
 cat >/var/cache/slack/roles/slapjob$$/scripts/postinstall <<__EOF__
@@ -276,16 +302,34 @@ slack --no-sync --sleep 3600 slapjob$$
 SLACKSTATUS=$?
 if [ "X${SLACKSTATUS}" != "X0" ] ; then
  if [ "X${__OSNAME}" = "XSunOS" ] ; then
-  /usr/sbin/slack-slaper sysupdate.report
-  /usr/sbin/slack-slaper openldap-client
+  /usr/sbin/slack-get sysupdate.report
+  /usr/sbin/slack-get openldap-client
  else
-  /usr/sbin/slack-slaper sysupdate.report
+  /usr/sbin/slack-get sysupdate.report
  fi
 fi
 
 }
 
 reporttemplate()
+{
+if [ "X${REPORTZIP}" = "X" ] ; then
+ echo "REPORTZIP is null"
+ exit 1
+fi
+
+if [ ! -f "${REPORTZIP}" ] ; then
+ echo "Error in:{REPORTZIP}"
+ echo "file not found."
+ exit 1
+fi
+
+wget -t 10 -T 10 -w 3 --waitretry=3 --random-wait "http://foo/cgi-bin/sysrpt.sh?${REPORTZIP}" -O -
+return $?
+}
+
+
+ldapreporttemplate()
 {
 if [ "X${CKSUM}" = "X" ] ; then
  echo "CKSUM is null"
